### ISSUE TITLE
Arrow on template node

### ISSUE THREAD

**Issue by fab33** [node-red/node-red-dashboard#27]
It will be better fo UI to set overflow-y to auto in .nd-dashboard-template class (file : node-red-dashboard/src/components/ui-component/templates/template.css) Line 3.

**Comment by dceejay** [comment]
tried both... not seeing any difference with chrome and firefox... what do you see ?

**Comment by fab33** [comment]
![screenshot at 2016-06-16 23 35 45](https://cloud.githubusercontent.com/assets/10790326/16134013/3ae63860-341b-11e6-9a4c-1d3740aea21b.png)

**Comment by dceejay** [comment]
Is that the 0.14.0 branch ?   - Changed it in that now. - but seems ok anyway.

Side topic - Actually the switch can have two states - so that could be used rather than template for simple indicators... - as long as the click action was disabled... ??? would that be something useful ?

**Comment by fab33** [comment]
Screenshot is from master branch. I will check with last branch later.
And for the side topic, I thnk It will ver useful to have icon with action disable. (And it will be fine to have more than 2 states.
For heaters in France we have 6 states and usualy only 3 inplemented (Confort, Eco, Frost)
And another related question, can we use other icons ?

**Comment by dceejay** [comment]
OK, thanks. 
Hmm, 6 states.. easier to do in a template ! 😀

**Comment by roadfox** [comment]
i get those "arrows" on every template node when i add an <img src= you can have a look here: http://node.aironaut.ch:1880/ui/#/0
do i understand right, this is fixed in the latest version?

**Comment by dceejay** [comment]
fixed in latest 0.14.0 branch.

**Comment by roadfox** [comment]
hmm sorry for my noob questions then, i did a "git pull" and it shows me that i'm on 0.14.0
restartet node-red but still get this scroll bar on the right. do i have to change something in the template as well?

**Comment by dceejay** [comment]
v 0.14.0 of the dashboard project ?  I went to your page and I see no bars
![image](https://cloud.githubusercontent.com/assets/5375409/16149601/e0061324-3489-11e6-9dd4-32aabb976e45.png)

**Comment by roadfox** [comment]
thats strange, i get in firefox:
![bild 3](https://cloud.githubusercontent.com/assets/1335878/16169520/885710f2-3532-11e6-9c15-acb57ae11307.png)
in edge:
![bild 4](https://cloud.githubusercontent.com/assets/1335878/16169522/9274e942-3532-11e6-8469-7282dfea05c4.png)
and in chrome:
![bild 5](https://cloud.githubusercontent.com/assets/1335878/16169525/996c47d6-3532-11e6-80f2-c68ad7f0480c.png)

**Comment by dceejay** [comment]
Which OS are you using ?

**Comment by roadfox** [comment]
As clinet? I'm using Windows 10, but it's the same on FF on W2008R2, as server i'm on ubuntu 14.04
I'm not very confident with git, so i'm not 100% sure i update dashboard right. I git chekedout dashboard as per description, then just enterred that directory and did "git pull origin master" if i do this again i get: 
`git pull origin master`
`From https://github.com/node-red/node-red-dashboard`
` * branch            master     -> FETCH_HEAD`
`Already up-to-date.`
i had node-red-contrib-ui installed before, but deleted the folder node_modules
should i better delete node-red-dashboard and checkout from scratch?
