### ISSUE TITLE
Switch Node does not show state correctly

### ISSUE THREAD

**Issue by Harpau** [node-red/node-red-dashboard#497]
If I add the Dashboard link to the Homescreen of my iPhone and open the Dashboard by clicking the Icon created on the Homescreen then all charts are shown again with a legend.
If I open the Dashboard using a Bookmark in Safari it works well.
I have cleared the cache in the Safari Settings and I have created the Link on the Homescreen completely new, but it does not work reproducible.
With the previous Versions this didn’t occur.
Many thanks again for your continuing support.
Harald

**Comment by dceejay** [comment]
Works fine here - again I suspect you have some sort of cacheing issue.

**Comment by Harpau** [comment]
Dear Dave,

Many thanks.
Please have a look on what I am doing step by step in order to reproduce this error:

Delete all existing Dashboard Homescreen Icons/Links
Close all Safari Windows
Close all Apps
Clear Website Data in Safari Settings
Make sure, Website Data is 0 Byte
Turn off iPhone completely
Turn it on again (cold start)
Check again if Website Data is still 0 Byte
Open Dashboard in new Safari Window

è Works fine: No Legend is shown
Perform “Add to Homescreen”
Click new created Dashboard Icon on Homescreen

è Does not work correctly: Legend is shown

Do you have any idea what I might be doing wrong?

Best regards

Harald

____________________________________________________

COMPESO GmbH
Carl-Zeiss-Ring 9
D 85737 Ismaning
Tel.: +49 (0)89 / 96 97 97 - 77
Fax: +49 (0)89 / 96 97 97 - 97

WWW.COMPESO.COM<blocked::http://www.compeso.com/>

COMPESO Computerperipherie und Software GmbH
Sitz der Gesellschaft: Ismaning, Landkreis München - Amtsgericht München HRB 73627
Geschäftsführer/Managing Director: Dipl. Ing. Harald Paulus USt-IdNr./VAT-IdNo.: DE 129320242


Von: Dave Conway-Jones [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. Mai 2019 09:41
An: node-red/node-red-dashboard <node-red-dashboard@noreply.github.com>
Cc: Paulus, Harald <hpaulus@compeso.com>; Author <author@noreply.github.com>
Betreff: Re: [node-red/node-red-dashboard] Legend is shown even if Legend Option set to "None" when opening by a Homescreen Link on iPhone (#497)


Works fine here - again I suspect you have some sort of cacheing issue.

**Comment by dceejay** [comment]
sorry - no I'm not an expert on iphone safari/home screen cacheing - google is probably a better bet.

**Comment by Harpau** [comment]
The point is: Until version 2.15.1, it definitely worked perfectly on my iPhone.

**Comment by dceejay** [comment]
indeed there was a bug in 2.15.0 that was fixed in 2.15.2. Using 2.15.2 on my iphone homescreen (having not tried 2.15.0 so nothing cached anywhere) I can see that the legend can be turned on and off from the server side and the client behaves as it should.

**Comment by Harpau** [comment]
Indeed it seems to be a – still not solved - problem of iOS: https://forums.developer.apple.com/message/105104#105104

According to the last post in this thread “Why all this trouble? Can't you just set the page(s) server side to expire last visits and force new pulls after x min/hours/days?” may I ask if there is anything possible to do from server side to force iOS loading the new version and not to use the cached data?

Many thanks again, Harald

**Comment by Harpau** [comment]
Is it possible, that there is an issue in the new version with caching at all?
I now noticed a strange behaviour of the Switch Node as well: It does not show the right value when opening a page. After a few minutes, while leaving the page untouched, it shows step by step the right values! Only the switch “Umwälzung” shows continuously the wrong value. The enclosed screenshots are taken on my PC running Google Chrome and in chronological order – please have a look on the timestamps.

**Comment by Harpau** [comment]
![2019-05-16 (4)](https://user-images.githubusercontent.com/47887931/57852539-b6394980-77e3-11e9-892d-d1b45fc3fe04.png)
![2019-05-16 (5)](https://user-images.githubusercontent.com/47887931/57852545-ba656700-77e3-11e9-982b-c9af58e101b0.png)
![2019-05-16 (6)](https://user-images.githubusercontent.com/47887931/57852562-c2bda200-77e3-11e9-82f6-9f615e0e7226.png)
![2019-05-16 (7)](https://user-images.githubusercontent.com/47887931/57852590-d10bbe00-77e3-11e9-91c1-c7ae49b73a06.png)

**Comment by dceejay** [comment]
Not as far as I know.  This new problem is nothing to do with cacheing of web page widgets / js / css files. I notice you have many nodes there that are not core nodes so I am unable to help with those or if they have any bearing on the situation. 

If you wish to discuss another problem it maybe best to raise it on the public discourse forum as a much wider group watch there and can possibly help.

**Comment by Harpau** [comment]
Please excuse me if I'm annoying: I have now set a switch node before the chart node and set msg.ui_control.options.legend.display to false. Now the chart is displayed without a legend.

**Comment by dceejay** [comment]
yes the broken version worked if you do that - it was the flag from the ui it was ignoring. Works if you override it. So yes that ia workaround for you, but others that haven't got a bad cache won't need it.

**Comment by Harpau** [comment]
OK, regarding the Switch Node issue, I have tried it with a very simple test flow now:

`[{"id":"7f81fb86.10e664","type":"inject","z":"91330dca.821c3","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":true,"onceDelay":"2","x":90,"y":200,"wires":[["d5576ece.10911","5dd9f6a2.86ad08"]]},{"id":"d5576ece.10911","type":"debug","z":"91330dca.821c3","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":330,"y":260,"wires":[]},{"id":"5dd9f6a2.86ad08","type":"ui_switch","z":"91330dca.821c3","name":"","label":"Test","tooltip":"","group":"1560620a.8febce","order":0,"width":0,"height":0,"passthru":false,"decouple":"true","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":310,"y":140,"wires":[[]]},{"id":"1560620a.8febce","type":"ui_group","z":"","name":"Test","tab":"ee5c0835.2b15d8","disp":true,"width":"6","collapse":false},{"id":"ee5c0835.2b15d8","type":"ui_tab","z":"","name":"Test","icon":"dashboard","disabled":false,"hidden":false}]`

Now I open Node Red and leave the Dashboard closed. I press the Inject Button. The State of the Switch Node becomes "ON". I open the Dashboard and the Switch shows "OFF". I press again the Inject Button while leaving the Dashboard open and the Switch goes to "ON". If I close the Dashboard and open it again, the Switch shows again "OFF".

**Comment by dceejay** [comment]
OK - so that is a proper bug - can you edit the title of this thread to reflect this issue.
