### ISSUE TITLE
Swiping between tabs doesn't work on PC or Mac anymore

### ISSUE THREAD

**Issue by fdnic99** [node-red/node-red-dashboard#712]
I always used swipe navigation between tabs on the dashboard, because i wanted a clean display with just buttons and informations and without any visible menus. 

Today i updated all components (Node.JS, NodeRed, all installed packages ) to the latest versions. 
Now swiping between tabs doesn't work anymore with any browser on PC or Mac. 

But it is still working on mobile devices. 

### What are the steps to reproduce?

1. Select "Allow swipe between tabs" in Dashboard > Site > Options - settings
2. Make a Full Deploy
3. Open dashboard on any PC or Mac browser
4. Try to swipe beween tabs using click and holding mouse button while swiping to the left or to the right

### What happens?

At mobile devices swiping between tabs works as before, but on  PC / Mac nothing happens. :-(

### What do you expect to happen?

swiping to the next / previous tab

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.30.0
- [ ] Node-RED version: 1.3.5
- [ ] node.js version: 14.17.2
- [ ] npm version: 6.14.13
- [ ] Platform/OS: RPi (NodeRed), Browsers (Windows 10 / OS X)
- [ ] Browser: Windows: Chrome, FF, Edge / Mac: Safari, Chrome

**Comment by davies8172** [comment]
I have just noticed this on my dashboard today. I often use a laptop (while I'm at work) to view my dashboard and now I've had to enable icons so I can change between pages as swiping does not work anymore.
Any help is greatly appreciated.
Same version as mentioned above too.
- Node-RED-Dashboard version: 2.30.0
- Node-RED version: 1.3.5
- Node.js version: 14.17.2
- npm version: 6.14.13
- Platform/OS: RPi (NodeRed), Browsers (Windows 10 / OS X)
- Browser: Windows: Chrome, FF

**Comment by dceejay** [comment]
This was caused by a fix in the latest release that allows you to drag select text in widgets so it can be copied and pasted etc. Basically it disables swipe with mouse - and just allows swipe with touch. So far I can't find a way for angular to dynamically apply the class `ng-swipe-disable-mouse` so that it could be switchable.

**Comment by dceejay** [comment]
I have pushed an update to master that gives an option to allow mouse swipe as well - but for me it seems very inconsistent in behaviour despite the source looking correct.

**Comment by fdnic99** [comment]
Meanwhile i updated Node RED to v2.0.5 but the problem is still there as Dashboard version is still v2.30.0.  

I also recognized, that on Mac using Safari, swiping is working ... even by using a mouse. 
But it's not working, when i use Chrome on the Mac. 

Additional Information - my Dashboard Site Options are:
- Hide the title bar
- Click to show side menu
- Allow to swipe between tabs
- Node-RED theme everywhere 
  
It would be very cool to have an extra option to maintain the swiping functionality. 
Otherwise the Option "Allow to swipe between tabs" wouldn't make any sense for desktop-users. 

In my case drag&drop of input texts is not needed.

**Comment by rf7e** [comment]
still a problem for me in 2025 ...
trying to migrate from nodered 3.02 and node-red-dashboard v1

now:
@flowfuse/node-red-dashboard 1.22.1
node-red 4.0.8

cannot swipe on PC Desktop
any solution ?

**Comment by dceejay** [comment]
you will need to raise this as a feature request on the new dashboard project. No point in leaving it here as it won't get fixed on the v1 dashboard.
